### PR TITLE
Fixed broken links to documentation

### PR DESCRIPTION
**Pull request by kernfel**

### CODE REVIEW

**Review by tnowotny — APPROVED** [review]
Hi Felix, good catch there - completely missed this implication of changing our main webpage.

**Comment by tnowotny** [comment]
oops ... I slightly missed the point - @kernfel , these pages are generated with nikola from the src branch. I have applied your fix to the relevant index.html source file in the src branch and deployed with nikola which should fix the issue.

**Comment by kernfel** [comment]
Ah, gotcha. I saw those nikola autocommit messages, but didn't quite understand where the source comes from, obviously. Sorry!

**Comment by tnowotny** [comment]
no problem - as you can see I got myself confused for a moment ;-)

**Pull request merged**
